# Generated by Django 4.1 on 2023-04-05 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, unique=True, verbose_name='number')),
                ('owner', models.CharField(max_length=100, verbose_name='owner')),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date released')),
                ('date_expired', models.DateTimeField(verbose_name='date expired')),
                ('balance', models.FloatField(verbose_name='balance')),
                ('is_activated', models.BooleanField(default=False, verbose_name='activated')),
                ('is_expired', models.BooleanField(default=False, verbose_name='expired')),
            ],
        ),
    ]
