# Generated by Django 4.1 on 2023-04-07 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('bonus', models.FloatField(verbose_name='bonus')),
                ('balance', models.FloatField(verbose_name='balance')),
                ('date_used', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date used')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card')),
            ],
        ),
    ]
